log_dir : D:\\Stock_Selection_and_Portfolio_Optimization_System_for_Pure_Equity_Mutual_Funds\\logs
artifact: D:\\Stock_Selection_and_Portfolio_Optimization_System_for_Pure_Equity_Mutual_Funds\\artifact
data : D:\\Stock_Selection_and_Portfolio_Optimization_System_for_Pure_Equity_Mutual_Funds\\data